# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "xhci_pci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f00f0b69-8e0a-44a5-9ea7-35ec15f2d2b4";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3e2171eb-ae97-42e7-944b-f6ecf4934cfb";
      fsType = "ext4";
    };

# vfat doesn't have file permissions so we have to add the rw and user flags
  fileSystems."/backup" =
    { device = "/dev/disk/by-uuid/E17B-5AE1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "uid=1000" "gid=1000" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/65FD-1CC5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "uid=1000" "gid=1000" ];
    };

# connecting to a smb drive
  fileSystems."/nas/richard" =
    { device = "//192.168.1.183/richard";
      fsType = "cifs";
      options = [ "credentials=/etc/credentials/.nas" "uid=1000" "gid=1000" ];
    };

  fileSystems."/nas/linda" =
    { device = "//192.168.1.183/linda";
      fsType = "cifs";
      options = [ "credentials=/etc/credentials/.nas" "uid=1000" "gid=1000" ];
    };
    
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
